
# Template
# GIS_COLLECTION = [
#     {
#         "file": "",
#         "description": "",
#         "continent": "",
#         "country": "",
#         "area_name": "",
#         "year": "",
#         "month": "",
#         "day": "",
#         "time": "",
#         "type": "GEOPARQUET"
#     },
#     {
#         "file": "",
#         "description": "",
#         "continent": "",
#         "country": "",
#         "area_name": "",
#         "year": "",
#         "month": "",
#         "day": "",
#         "time": "",
#         "type": "GEOTIFF"
#     },
# ]

GIS_COLLECTION = [
    {
        "file": "/data/hotspot_2024.parquet",
        "description": "Hotspots in Thailand for the year 2024",
        "continent": "ASIA",
        "country": "THAILAND",
        "area_name": "",
        "year": "2024",
        "month": "Jan to May",
        "day": None,
        "time": None,
        "type": "GEOPARQUET"
    },
    {
        "file": "/data/hotspot_2025.parquet",
        "description": "Hotspots in Thailand for the year 2025",
        "continent": "ASIA",
        "country": "THAILAND",
        "area_name": "",
        "year": "2025",
        "month": "01 - 05",
        "day": None,
        "time": None,
        "type": "GEOPARQUET"
    },
    {
        "file": "/data/burnscar_2024_01.parquet",
        "description": "Burnscar in Thailand for the year 2024",
        "continent": "ASIA",
        "country": "THAILAND",
        "area_name": "",
        "year": "2024",
        "month": "Jan",
        "day": None,
        "time": None,
        "type": "GEOPARQUET"
    },
    {
        "file": "/data/burnscar_2024_02.parquet",
        "description": "Burnscar in Thailand for the year 2024",
        "continent": "ASIA",
        "country": "THAILAND",
        "area_name": "",
        "year": "2024",
        "month": "Feb",
        "day": None,
        "time": None,
        "type": "GEOPARQUET"
    },
    {
        "file": "/data/burnscar_2024_03.parquet",
        "description": "Burnscar in Thailand for the year 2024",
        "continent": "ASIA",
        "country": "THAILAND",
        "area_name": "",
        "year": "2024",
        "month": "Mar",
        "day": None,
        "time": None,
        "type": "GEOPARQUET"
    },
    {
        "file": "/data/burnscar_2024_04.parquet",
        "description": "Burnscar in Thailand for the year 2024",
        "continent": "ASIA",
        "country": "THAILAND",
        "area_name": "",
        "year": "2024",
        "month": "Apr",
        "day": None,
        "time": None,
        "type": "GEOPARQUET"
    },
    {
        "file": "/data/burnscar_2025_01.parquet",
        "description": "Burnscar in Thailand for the year 2025",
        "continent": "ASIA",
        "country": "THAILAND",
        "area_name": "",
        "year": "2025",
        "month": "Jan",
        "day": None,
        "time": None,
        "type": "GEOPARQUET"
    },
    {
        "file": "/data/burnscar_2025_02.parquet",
        "description": "Burnscar in Thailand for the year 2025",
        "continent": "ASIA",
        "country": "THAILAND",
        "area_name": "",
        "year": "2025",
        "month": "Feb",
        "day": None,
        "time": None,
        "type": "GEOPARQUET"
    },
    {
        "file": "/data/burnscar_2025_03.parquet",
        "description": "Burnscar in Thailand for the year 2025",
        "continent": "ASIA",
        "country": "THAILAND",
        "area_name": "",
        "year": "2025",
        "month": "Mar",
        "day": None,
        "time": None,
        "type": "GEOPARQUET"
    },
    {
        "file": "/data/burnscar_2025_04.parquet",
        "description": "Burnscar in Thailand for the year 2025",
        "continent": "ASIA",
        "country": "THAILAND",
        "area_name": "",
        "year": "2025",
        "month": "Apr",
        "day": None,
        "time": None,
        "type": "GEOPARQUET"
    },
    {
        "file": "/data/rainfall_2025_01_cog.tiff",
        "description": "Rainfall in Thailand for the year 2025",
        "continent": "ASIA",
        "country": "THAILAND",
        "area_name": "",
        "year": "2025",
        "month": "01",
        "day": "",
        "time": "",
        "type": "GEOTIFF"
    },
    {
        "file": "/data/rainfall_2025_02_cog.tiff",
        "description": "Rainfall in Thailand for the year 2025",
        "continent": "ASIA",
        "country": "THAILAND",
        "area_name": "",
        "year": "2025",
        "month": "02",
        "day": "",
        "time": "",
        "type": "GEOTIFF"
    },
    {
        "file": "/data/rainfall_2025_03_cog.tiff",
        "description": "Rainfall in Thailand for the year 2025",
        "continent": "ASIA",
        "country": "THAILAND",
        "area_name": "",
        "year": "2025",
        "month": "03",
        "day": "",
        "time": "",
        "type": "GEOTIFF"
    },
    {
        "file": "/data/rainfall_2025_04_cog.tiff",
        "description": "Rainfall in Thailand for the year 2025",
        "continent": "ASIA",
        "country": "THAILAND",
        "area_name": "",
        "year": "2025",
        "month": "04",
        "day": "",
        "time": "",
        "type": "GEOTIFF"
    },
    {
        "file": "/data/rainfall_2024_01_cog.tiff",
        "description": "Rainfall in Thailand for the year 2024",
        "continent": "ASIA",
        "country": "THAILAND",
        "area_name": "",
        "year": "2024",
        "month": "01",
        "day": "",
        "time": "",
        "type": "GEOTIFF"
    },
    {
        "file": "/data/rainfall_20254_02_cog.tiff",
        "description": "Rainfall in Thailand for the year 2024",
        "continent": "ASIA",
        "country": "THAILAND",
        "area_name": "",
        "year": "2024",
        "month": "02",
        "day": "",
        "time": "",
        "type": "GEOTIFF"
    },
    {
        "file": "/data/rainfall_2024_03_cog.tiff",
        "description": "Rainfall in Thailand for the year 2024",
        "continent": "ASIA",
        "country": "THAILAND",
        "area_name": "",
        "year": "2024",
        "month": "03",
        "day": "",
        "time": "",
        "type": "GEOTIFF"
    },
    {
        "file": "/data/rainfall_2024_04_cog.tiff",
        "description": "Rainfall in Thailand for the year 2024",
        "continent": "ASIA",
        "country": "THAILAND",
        "area_name": "",
        "year": "2024",
        "month": "04",
        "day": "",
        "time": "",
        "type": "GEOTIFF"
    },
]