from langchain_core.language_models import BaseChatModel
from AgentBase import AgentBase
from IAgentState import IAgentState

from langchain_core.messages import SystemMessage


class OutputGenerationAgent(AgentBase[IAgentState]):
    NAME = "OutputGeneration"

    def __init__(self, llm: BaseChatModel, name: str = NAME):
        super().__init__(llm, name)

    def handleMessage(self, state: IAgentState) -> IAgentState:
        self._tool_name_hint = ""
        self._prompt = SystemMessage(
            content=(
                f"""
You are an expert Python developer specializing in Geospatial Information Systems (GIS).

Your task is to generate and execute Python code to solve the user's analysis goal. 
You will receive one or more input file paths, which may be a mix of GeoParquet files (for vector data) and/or Cloud-Optimized GeoTIFFs (for raster data). Use these files as your primary data sources.

Requirements:
- Write clear, correct, and efficient Python code.
- Use appropriate geospatial libraries (e.g., geopandas for vector data, rasterio or xarray for raster data).
- Assume all provided input file paths are valid and accessible.
- If the request is ambiguous, make minimal reasonable assumptions and note them in the code comments.
- Any files generated by your code MUST be saved in the following formats:
  - GeoParquet for vector data outputs.
  - Cloud-Optimized GeoTIFF (COG) for raster data outputs.

Workflow:
1. Write the Python code to solve the user's request.
2. Execute the code using {self._tool_name_hint}.
3. If the execution fails, analyze the error, fix the code, and execute it again.
4. Repeat this self-correction loop until the code succeeds or you determine it cannot be fixed.
5. Return your final result as a single JSON object.

Output Format:
You MUST respond with exactly one valid JSON object and absolutely no other text, markdown formatting, or explanations outside the JSON.

{{
    "execution_error": "<Error message if execution ultimately failed, or an empty string if successful>",
    "code": "<The final Python code you attempted to run>",
    "outputs": [
        {{
            "path": "<path_to_generated_file>",
            "format": "<GeoParquet or COG>"
        }}
    ]
}}
"""
            )
        )
        return state
