from datetime import datetime, timezone
from typing import Any, Dict, List, Literal, Optional
from uuid import uuid4

from pydantic import BaseModel

from AgentBase import ObservableState


class GISFile(BaseModel):
    path: str
    ftype: Literal["GEOPARQUET", "GEOTIFF"]
    description: str


class OpOutput(BaseModel):
    output_type: Literal["GEOPARQUET_LAYER", "GEOTIFF_LAYER", "REPORTS", "CHARTS"]
    description: str
    path: str


# Shared inter-agent state contract.
class IAgentState(ObservableState):
    query_summary: str
    user_language: str
    is_query_accepted: bool
    # Shared so main graph terminal state can carry IR/OP declines end-to-end.
    decline_message: Optional[str]
    # Shared so interrupt-capable nodes can expose pending clarifications.
    clarification_question: Optional[str]
    selected_layers: Optional[List[GISFile]]
    code: str
    outputs: Any


class IrState(IAgentState):
    clarification_question: Optional[str]
    gis_related: Optional[bool]
    decline_message: Optional[str]
    general_layers: Optional[bool]


class OpState(IAgentState):
    clarification_question: Optional[str]
    decline_message: Optional[str]
    outputs: Optional[List[OpOutput]]
    code: Optional[str]
    # Guardrail flag: OP returned code without observed tool execution.
    op_requires_tool_call: Optional[bool]


class SessionModel(BaseModel):
    # Used by SessionService for session lifecycle and metadata storage.
    sessionId: str
    status: Literal["active", "closed"] = "active"
    createdAt: str
    lastRunId: Optional[str] = None

    @classmethod
    def create(cls) -> "SessionModel":
        return cls(
            sessionId=f"sess_{uuid4().hex[:12]}",
            status="active",
            createdAt=datetime.now(timezone.utc).isoformat(),
        )


class LayerSource(BaseModel):
    # Used by LayerDescriptor; read/written by LayerService.
    type: str
    url: str


class LayerStyle(BaseModel):
    # Used by LayerDescriptor and LayerPatchRequest; managed by LayerService.
    preset: Optional[str] = None
    paint: Optional[Dict[str, Any]] = None
    layout: Optional[Dict[str, Any]] = None


class LayerDescriptor(BaseModel):
    # Used by LayerService as the canonical layer record returned by layer APIs.
    id: str
    name: str
    kind: Literal["geojson", "vector", "raster", "cog", "wms"]
    source: LayerSource
    style: LayerStyle
    visible: bool = True
    opacity: Optional[float] = None
    bounds: Optional[List[float]] = None
    origin: Literal["input", "agent_output"]
    createdByRunId: Optional[str] = None
    createdAt: str


class LayerPatchRequest(BaseModel):
    # Request body for PATCH /api/layers/{layer_id}
    # Consumed by LayerService.update_layer(...).
    visible: Optional[bool] = None
    opacity: Optional[float] = None
    style: Optional[LayerStyle] = None


class ChatRequest(BaseModel):
    # Request body for POST /api/sessions/{session_id}/chat
    # Consumed by RunService.execute_run(...).
    message: str
    context: Optional[Dict[str, Any]] = None


class ResumeRunRequest(BaseModel):
    # Request body for POST /api/runs/{run_id}/resume
    # Used specifically for HITL clarification continuation.
    # The interruptId must match the pending LangGraph interrupt instance id.
    interruptId: str
    # User clarification answer for the pending interrupt.
    answer: str


class RunModel(BaseModel):
    # Used by RunService for run status tracking and polling responses.
    runId: str
    sessionId: str
    status: Literal["queued", "running", "completed", "failed", "interrupted"]
    startedAt: str
    finishedAt: Optional[str] = None
    error: Optional[str] = None
    # Durable decline reason for terminal catch-up when SSE subscribers attach late.
    declineMessage: Optional[str] = None
    # Generated by LangGraph for a specific interrupt occurrence; backend stores
    # and forwards it back in Command(resume={interrupt_id: answer}).
    pendingInterruptId: Optional[str] = None
    # Human-readable question associated with pendingInterruptId.
    pendingQuestion: Optional[str] = None
